cilium/hubble-ui

server/src/server/k8s.ts
Related to `skipTLSVerify`, probably will help with ssl issues
=> Added STRICT_SSL env var

server/src/db.ts, server/src/dbHubble.ts, server/src/resolversImpl.ts
- filter out reserved labels
- filter out non forwarded status
=> Improvement: reduce amount of flows for service map discovery

server/src/configDbHubble.ts, server/src/dbHubble.ts, server/src/server/k8s.ts
- try to setup config for serviceAccount case at first place
- fallback to default method if not succeeded
- setup skipTLSVerify prop for cluster
- correctly setup strictSSL prop for requests
Signed-off-by: Dmitry Kharitonov <geakstr@me.com>
=> improved k8s rest api config setup

client/src/components/Map/NamespaceBackplate.tsx, client/src/components/Map/index.tsx, client/src/domain/layout.ts, client/src/store/stores/layout.ts, package.json
* Card rendering optimization
* Linter rules fixed not to look outside of `src/` directory
=> fix: a huge optimization not to rerender Cards on Map

client/src/api/index.ts, client/src/api/mock.ts, client/src/components/AccessPoint/index.tsx, client/src/components/AccessPoint/styles.scss, client/src/components/App/index.tsx, client/src/components/EndpointCard/EndpointCardContent.tsx, client/src/components/EndpointCard/styles.scss, client/src/components/Map/index.tsx, client/src/domain/service-card.ts, client/src/domain/service-map.ts, client/src/store/stores/interaction.ts, client/src/store/stores/layout.ts, client/src/store/stores/main.ts, client/src/store/stores/service.ts
=> feat: rendering access points on cards (port / protocol point)

.github/workflows/build.yml
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>
=> actions: Run actions on release branches/tags

.github/workflows/build.yml
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>
=> actions: Fix branch/tag patterns

client/src/components/ArrowsRenderer/index.tsx, client/src/components/EndpointCard/EndpointCardBase.tsx, client/src/components/EndpointCard/EndpointCardContent.tsx, client/src/components/EndpointCard/general.ts, client/src/components/Map/index.tsx, client/src/domain/layout.ts, client/src/store/stores/layout.ts
* FIX: update start plates when card is moving
* FIX: connections and connectors indices
* FIX: card placement algorithm is formed with robust entities
* FIX: do not place world related cards into namespace rectangle
* FIX: do not violate arrows rendering when another namespace is selected (and map moved / resized)
=> fix: well-formed algorithm for cards placement

.gitmodules, Dockerfile, server/generate.sh
For now just use HEAD of the master branch of Cilium repo.
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>
=> Use protobuf definitions from cilium instead of hubble

client/src/api/flows-stream.ts
=> fix: fixed from/to flows filters

client/src/api/general/event-stream.ts, client/src/api/grpc/event-stream.ts, client/src/components/App/index.tsx, client/src/components/ArrowsRenderer/index.tsx, client/src/utils/emitter.ts, events-server/server/get-events.go
* FIX: pass all grpc errors to client (attempt to let client know when stream is closed)
* FIX: remove all event handlers from old stream when it is replaced
* FIX: minor rendering fix on map (feets rendering)
=> fix: prevent event stream from being used after parameters switch

client/src/components/App/index.tsx, client/src/components/ArrowsRenderer/index.tsx, client/src/components/DragPanel/styles.scss, client/src/components/EndpointCard/EndpointCardBackplate.tsx, client/src/components/EndpointCard/EndpointCardBase.tsx, client/src/components/EndpointCard/EndpointCardContent.tsx, client/src/components/EndpointCard/EndpointCardLabels.tsx, client/src/components/EndpointCard/styles.scss, client/src/components/EndpointCardHeader/index.tsx, client/src/components/FlowsTable/ColumnsSelector.tsx, client/src/components/InputElements/ForwardingStatusDropdown.tsx, client/src/components/InputElements/HttpStatusCodeDropdown.tsx, client/src/components/Map/NamespaceBackplate.tsx, client/src/components/Map/index.tsx, client/src/components/Map/styles.scss, client/src/components/TopBar/NamespaceDropdown.tsx, client/src/domain/service-card.ts, client/src/store/stores/layout.ts, client/src/ui/hooks/usePopover.ts, client/src/ui/hooks/useZoom.ts
- refactored Map components to not use global store
- usePopover hook for all popovers to make them controllable
- hide popovers on map clicks as well
- full card is clickable now, not only header
- improved mouse cursor styles in different places
=> fix: misc fixes here and there

Dockerfile
Do not merge, depends on https://github.com/cilium/hubble-ui/pull/62
=> Use base cilium/hubble-ui-base image

client/src/components/ArrowsRenderer/index.tsx, client/src/domain/geometry/utils.ts, client/src/domain/geometry/vec2.ts, client/src/store/stores/layout.ts, client/src/utils/advancer.ts
* FEAT: arrows are now using gaps around receiver card
* FEAT: utility class `Advancer` to accumulate value by key
* FIX: geometry utils optimized (not using `Vec2`s)
* FIX: proper criteria for sweep flag on arrow handle rendering
* FIX: sharp angle eliminated at the end of arrow
=> feat: arrows are now using gaps around receiver card

client/src/api/__mocks__/data.ts, client/src/api/__mocks__/grpc.ts, client/src/api/general/event-stream.ts, client/src/components/AccessPoint/index.tsx, client/src/components/App/index.tsx, client/src/components/ArrowsRenderer/index.tsx, client/src/domain/flows/index.ts, client/src/domain/helpers/index.ts, client/src/domain/hubble.ts, client/src/domain/ids.ts, client/src/domain/layout.ts, client/src/domain/service-card.ts, client/src/domain/service-map.ts, client/src/store/stores/controls.ts, client/src/store/stores/interaction.ts, client/src/store/stores/layout.ts, client/src/store/stores/main.ts, client/src/store/stores/service.ts, client/src/ui/vars.ts
- showing mixed dropped/forwarded, dropped and forwarded flows
- cross-namespace bug fixed
=> feat: show dropped flows on service map

client/src/components/App/index.tsx, client/src/components/DetailsPanel/hooks/usePanelResize.ts, client/src/components/DetailsPanel/index.tsx, client/src/components/FlowsTable/Row.tsx
- fixed initial map centering
- fixed "Namespace "null" is still not observed ..."
- show ip for world if dns not exists
=> fixes: fixed map centering. namespace handling on first launch

.babelrc.js, .gitignore, package-lock.json, package.json, src/components/DetailsPanel/hooks/usePanelResize.ts, src/components/FlowsTable/hooks/useScroll.ts, src/domain/geometry/position.ts, src/ui/hooks/useDetectScroll.ts, src/ui/hooks/usePopover.ts, tsconfig.json
=> chore: tsconfig changes

backend/Dockerfile, backend/go.mod, backend/go.sum, backend/server/data-cache.go
=> Update dependencies and fix concurrent access of golang maps

backend/server/get-events.go
Signed-off-by: Sergey Generalov <sergey@genbit.ru>
=> logs: add additional info logging to the backend

src/api/grpc/event-stream.ts, src/api/grpc/index.ts, src/components/App/DataManager.ts, src/components/App/index.tsx, src/domain/filtering/filter-entry.ts, src/domain/filtering/index.ts, src/store/__tests__/frame.ts, src/store/frame.ts
* FIX: use correct flow filters for calling `GetFlows`
* FIX: do not leave orphaned services on the map when do local filtering
* FIX: do not recreate `GetEvents` stream on changing `Filters` reference
=> fix: bunch of fixes for flows streaming and local filtering

server/envoy.yaml
To sync config with https://github.com/cilium/cilium/pull/15847
=> upgrade envoy config for newer versions

server/envoy.yaml
=> envoy: fix config to keep grpc conn stable

Dockerfile, backend/Dockerfile
Signed-off-by: André Martins <andre@cilium.io>
=> Dockerfile: add do not upgrade alpine comments

src/components/App/index.tsx, src/components/DetailsPanel/index.tsx
Show additional message when connection is ok but there are still no flows in selected namespace
=> feat: improved flows pending state

backend/server/server.go
As official option to configure kubectl.
In multi cluster workflows configure kubectl via kubeconfig env var is very useful to avoid mistakes.
=> backend: support for KUBECONFIG env var

backend/main.go
=> feat: Add /healthz endpoint to prepare probes for Cilium chart
