cilium/hubble-ui

- server/package-lock.json
- server/package.json
- server/src/dbHubble.ts
Currently the ipv6 is broken for multiple reasons:
1. The kubernetes-client needs at least 0.11.1 to construct a correct URI with ipv6
see https://github.com/kubernetes-client/javascript/issues/380
2.  dns.resolve4 is used in [dbHubble.ts:244](https://github.com/cilium/hubble-ui/blob/15e8cd01287b0ef26079d7746885322813b6ea12/server/src/dbHubble.ts#L244)
3. If the kubernetes URI contains an ipv6 plus the 443 port the request will fail to verify the TLS
see issue https://github.com/request/request/issues/3274)
This PR address the 2 first points, as the third still need to be fixed in request
> Makes hubble-ui working with ipv6

- Dockerfile
- patches/request_issue3274.patch
Following https://github.com/cilium/hubble-ui/pull/7
Adds a patch for request to workaround an issue with TLS and IPv6
see request/request#3274
This can be removed once the patch is merged upsteam.
> Patch request to workaround request/request#3274

- server/src/dbHubble.ts
this is an simple attempt to unblock node.js from calling `on("data")` callback all the time while flows are coming. we try to do it for a scale debugging purposes
also this pr removes the hack around flows receiving timeout, this was fixed on hubble side https://github.com/cilium/hubble/pull/102
Signed-off-by: Dmitry Kharitonov geakstr@me.com
> reorder grpc callbacks setup

- client/src/hooks/useForceUpdate.ts
Hi,
I used this kind of hook useForceUpdate, but after one month I found the next error.
https://monosnap.com/file/4Wvg626bqImtDHx3sAy9EpM5OB0P4Y
I cant found minimal code for reproducing this error because simple cases worked without any errors. Full code who reproducing that error:
https://codesandbox.io/s/wonderful-star-e50rl
Possible fix:
```typescript
const reducer = (state: number, _action: null): number => (state + 1) % 0xffffff;
```
https://github.com/betula/lamp-luwak/blob/6e8d704ee425ff18d4eaaf36a48ba97bad6498f3/src/useForceUpdate.ts#L5
The error was disappeared after that fix.
https://monosnap.com/file/83MRDHxOEHEgUCyhrEW0es73GYFHlv
But very interested, when todo list has 3 lines, is ok worked without some error, only with even count of a todo list item.
> useForceUpdate hook fixed

- Dockerfile
**feat: non-root container**
Add EXPOSE directive to clearly indicate that the service
is being exposed at given port
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
**Note:**
Tested on k8s (`v1.18`) with enforced  [restricted PSP](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies)
> feat: non-root container

- client/src/__tests__/App.test.tsx
- client/src/components/App/index.tsx
- client/src/components/FlowsTable/Row.tsx
- client/src/components/FlowsTable/__tests__/Row.test.tsx
- client/src/components/FlowsTable/index.tsx
- client/src/testing/data/flows.ts
- client/src/testing/data/index.ts
- client/src/testing/index.tsx
- client/tsconfig.json
This PR suggests few changes on testing utils
- `@test-utils` moved to `~/testing`
- `~/testing` directory fulfilled with examples of testing (mock) data for flows
- `Row.tsx` is now separate component:
- It's simplier to read coverage report
- `Row.test.tsx` performs **not complete** testing on `Row` component:
- Timestamp field and css styling not tested yet (WIP)
- Each test performs whole bunch of interaction tests as well as visual tests, so that for any combination of input props we can be sure that there is no regress on other parts (interactions/styles/etc)
Signed-off-by: Renat Tuktarov renat@isovalent.com
> feat: initial code for testing most of the Row component (FlowsTable)

- client/src/components/EndpointCardHeader/index.tsx
- client/src/domain/service-card.ts
- events-server/server/service-cache.go
* FEAT: card header fixed to show proper service name (hide id, show id in case if it is world card)
> feat: external (world) cards now have id set to its domain names

- base.Dockerfile
Using a base docker image that we control we can upgrade it while
keeping reproducibility of builds for the top level Docker image.
Instead of using 'stretch' we should use the 'buster' debian version as
'scretch' is reaching EOL and 'buster' is the stable version.
Signed-off-by: André Martins <andre@cilium.io>
> add base Docker image

- Dockerfile
- package.json
I couldn't make grpc-tool work on Alpine. For now continue using Debian
for building, but use Alpine as the runtime image to avoid dealing with
security vulnerabilities.
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>
> Use Alpine as the runtime image

- client/src/api/general/event-stream.ts
- client/src/api/grpc/event-stream.ts
- client/src/components/App/DataManager.ts
- client/src/components/App/index.tsx
- client/src/domain/filtering/index.ts
- client/src/domain/flows/flows-filter-entry.ts
- client/src/domain/flows/index.ts
- client/src/domain/service-card.ts
- client/src/store/frame.ts
- client/src/store/index.ts
- client/src/store/stores/controls.ts
- client/src/store/stores/interaction.ts
- client/src/store/stores/layout.ts
- client/src/store/stores/main.ts
- client/src/store/stores/route.ts
- client/src/store/stores/service.ts
* FEAT: store now contains `StoreFrames` which represent layers of data
* FEAT: two getters are maintained inside `Store`: `currentFrame` and `mainFrame`
* FEAT: advanced functions to `clone` / `move` / `merge` data to/from different stores and entities
* FEAT: functions to make local filtration on data (`~/domain/filtering` module)
* FEAT: huge amount of control logic has been moved from App root to App `DataManager` which is a new component doing all whats needed on store frames, streams and events handlers
* FEAT: the data is squashed into main frame when there is no need to maintain secondary layer of data
* FIX: `Flow` class was fixed not to use generic `object-hash` hashing and use domain-specific data to generate flow id (I have a talk with @gandro about that). I strongly recommend …
> feat: do local data (flows / services / layout) filtering not to drop entire store

- client/src/api/grpc/event-stream.ts
- client/src/components/App/DataManager.ts
- client/src/components/App/index.tsx
- client/src/components/ArrowsRenderer/index.tsx
- client/src/components/EndpointCard/EndpointCardContent.tsx
- client/src/domain/filtering/index.ts
- client/src/domain/geometry/vec2.ts
- client/src/domain/helpers/index.ts
- client/src/domain/labels.ts
- client/src/domain/link.ts
- client/src/domain/service-card.ts
- client/src/domain/service-map.ts
- client/src/store/frame.ts
- client/src/store/stores/controls.ts
- client/src/store/stores/interaction.ts
- client/src/store/stores/layout.ts
- client/src/store/stores/main.ts
* FEAT: `Link` now has its own wrapper around domain `HubbleLink` type
* FEAT: `Labels` in service are now effectively calculated and cached
* FIX: do not render the same card connector multiple times
* FIX: physical connectors middle point is now correctly calculated
* FIX: proper reaction to toggle showKubeDNS, showHost controls (do not flush the map)
* FIX: updating of start plate coords has been fixed (it was wrong in some margin cases)
> fix: bunch of fixes

- client/src/components/App/index.tsx
- client/src/components/DetailsPanel/index.tsx
- client/src/components/FlowsTable/Body.tsx
- client/src/components/FlowsTable/Row.tsx
- client/src/components/FlowsTable/__tests__/Row.test.tsx
- client/src/components/FlowsTable/general.ts
- client/src/components/FlowsTable/hooks/useWhenOccured.ts
- client/src/components/FlowsTable/index.tsx
- client/src/domain/flows/index.ts
- client/src/store/frame.ts
- client/src/store/stores/interaction.ts
- client/src/store/stores/main.ts
- client/src/utils/emitter.ts
- client/src/utils/ticker.ts
* FEAT: new util class `Ticker` - emits named tick event during specified interval
* FIX: now `App` uses its own `ticker` to synchronize timestamp update in every `FlowsTable` `Row`
* FIX: properly sort flows when using mock data
> fix: App-level clock synchronizer for updating row timestamp

- src/components/App/DataManager.ts
- src/components/ArrowsRenderer/index.tsx
- src/domain/filtering/__tests__/filter-flow.test.ts
- src/domain/filtering/__tests__/filter-link.test.ts
- src/domain/filtering/__tests__/filter-service.test.ts
- src/domain/filtering/__tests__/filters-equality.test.ts
- src/domain/filtering/__tests__/general.ts
- src/domain/filtering/index.ts
- src/domain/flows/__tests__/FlowsFilterEntry.test.ts
- src/domain/flows/flows-filter-entry.ts
- src/domain/flows/index.ts
- src/domain/labels.ts
- src/testing/data/flows.ts
- src/testing/data/index.ts
- src/testing/data/links.ts
- src/testing/data/services.ts
- src/utils/iter-tools/__tests__/combinations.test.ts
- src/utils/iter-tools/combinations.ts
`npx jest ./src/domain/filtering/__tests__/ --coverage`
File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                                                                           
------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
domain/filtering       |   95.74 |    94.52 |   93.33 |   98.29 |                                                                                                                                                                             
index.ts              | …
> fix: tests for filtering module

- src/api/general/event-stream.ts
- src/api/general/index.ts
- src/api/grpc/event-stream.ts
- src/api/grpc/index.ts
- src/components/App/DataManager.ts
- src/components/App/index.tsx
- src/components/DetailsPanel/index.tsx
- src/components/FlowsTable/Sidebar.tsx
- src/components/FlowsTable/SidebarComponents.tsx
- src/components/FlowsTable/__tests__/Sidebar.test.tsx
- src/components/FlowsTable/general.ts
- src/components/FlowsTable/index.tsx
- src/domain/filtering/__tests__/filter-flow.test.ts
- src/domain/filtering/__tests__/filter-link.test.ts
- src/domain/filtering/__tests__/filter-service.test.ts
- src/domain/filtering/__tests__/filters-equality.test.ts
- src/domain/filtering/filters.ts
- src/domain/filtering/index.ts
- src/domain/flows/flows-filter-entry.ts
- src/domain/hubble.ts
- src/domain/labels.ts
- src/store/stores/controls.ts
* fix: `SidebarComponents` now have centralized logic, moved to parent component
* feat: `Filters` is now separate class with convenient methods
* fix: API now depends on domain `Filters` type instead of its own `DataFilters`, which was removed
> fix: SidebarComponents refactor + Filters is now separate component

- backend/server/get-events.go
This fix prevents `GetEvents` server method from eating cpu for 100%
> fix: do not unblock for/select loop in GetEvents

- Dockerfile
- backend/Dockerfile
In Alpine 3.11 and 3.13, 'nslookup' exits with the error code 1 if it
can't resolve all IPs for the search list defined in /etc/resolv.conf
However, it seems that Alpine 3.10 and 3.12 are not affected by this bug
and continue return the error code 0 if at least on of the domains in
the search list is resolved into an IP address. Thus, we will use the
latest Alpine image available for the 3.12 release series.
Signed-off-by: André Martins <andre@cilium.io>
> Dockerfile: use alpine 3.12

- backend/domain/labels/labels.go
These labels were added in ce76f206d8b7bb8d23a945b5d93c879de8d9bff2,
but only in TypeScript code and not the Go version.
> Make sure Go backend recognised `app.kubernetes.io` labels also

- src/api/grpc/common.ts
- src/components/AccessPoint/index.tsx
- src/components/FlowsTable/Sidebar.tsx
- src/components/FlowsTable/__tests__/Sidebar.test.tsx
- src/testing/data/flows.ts
This change adds ICMP information to the Service Map and Flows Table. 
It also improves the Destination Port and Protocol section in the Flows Sidebar. This conditionally renders the port and protocol's titles and content based on whether a flow's protocol is ICMP. Relevant tests are included.
Fixes: [#276](https://github.com/cilium/hubble-ui/issues/276)
Signed-off-by: Stacy Kim <stacy.kim@ucla.edu>
> feat: Add ICMP info on Service Map and Flows Table

- backend/internal/msg/logs.go
- backend/main.go
This PR addresses #360 that was raised by my colleague @saichovsky.
In this PR, I added the necessary code to handle the case where a SIGINT or SIGTERM is sent to the backend app.
> backend: Shut down HTTP Server when receiving signal

- src/api/grpc/common.ts
- src/components/TopBar/FlowsFilterInput.scss
- src/components/TopBar/FlowsFilterInput.tsx
- src/domain/filtering/__tests__/filter-entry.test.ts
- src/domain/filtering/__tests__/filter-flow.test.ts
- src/domain/filtering/__tests__/filter-link.test.ts
- src/domain/filtering/__tests__/filter-service.test.ts
- src/domain/filtering/filter-entry.ts
- src/domain/filtering/filter-flow.ts
- src/domain/filtering/filter-link.ts
- src/domain/filtering/filter-service.ts
FlowsFilterInput could accept negation(!) operator prefixed filters to exclude specified elements.
For example, type `!k8s:io.kubernetes.pod.namespace=ingress` to exclude pods from ingress namespace
This could be a solution for #240.
> frontend: support negative flow filter

- backend/go.mod
- backend/main.go
- backend/vendor/golang.org/x/net/http2/h2c/h2c.go
- backend/vendor/modules.txt
This pull request tries to solve [issue#452](https://github.com/cilium/hubble-ui/issues/452).
Based on [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc#arch-overview-grpc) the [gprc-web filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_web_filter#config-http-filters-grpc-web) just translates grpc-web sent over HTTP/1.1 to the same format over HTTP/2.
As grpc-web uses GRPC format (not for example JSON format used by [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway)), making the API compatible with HTTP/2 should be enough to solve the issue.
The `h2c.NewHandler` would handle h2c requests and simply forward HTTP/1.1 requests to the wrapped `http.Handler`.
The code should work with an …
> make `/api/` h2c compatible

- src/index.html
Browsers can automatically generate dark themes from light themes, but it often looks strange and Hubble is no exception. It's possible to opt out of automatic dark themes by explicitly declaring the theme as light.
https://developer.chrome.com/blog/auto-dark-theme/#using-a-meta-tag
Fixes: #664
> chore: opt out of auto dark theme

- .github/dependabot.yml
Let's try to reduce the number of dependabot PRs and merge them in a more timely manner.
> dependabot: run weekly and use grouped updates for Go and NPM dependencies

- .github/dependabot.yml
This updates the Dependabot config so the `ci/dependabot` and `dependencies` labels are properly set on pull requests.
> Update `dependabot.yml` config for label rules

- src/components/FlowsTable/Cell.tsx
- src/components/FlowsTable/Header.tsx
- src/components/FlowsTable/Row.tsx
- src/components/FlowsTable/general.ts
- src/storage/local/__tests__/store-restore.test.ts
The `Source Service` and `Destination Service` columns have slightly confusing names as they appear to be security identities rather than service identities, a non-existent concept.
This renames references of `Source Service` to `Source Identity` and `Destination Service` to `Destination Identity`.
Fixes: #249
> Rename Source and Destination `Service` to `Identity`

- src/components/ServiceMapArrowRenderer/ServiceMapArrowDuckFeet.tsx
No issue.
No matter what, the service map page were showing a scroll on Chrome. This PR removes it.
- Remove hidden elements from DOM's tree using `display: none` instead of `visibilitiy: hidden`
| Before | After |
|---|---|
|<img width="1362" alt="Screenshot 2024-02-08 at 11 51 25" src="https://github.com/cilium/hubble-ui/assets/1910449/1f468e29-5d01-4219-924e-bdac250e882f">|<img width="1196" alt="Screenshot 2024-02-08 at 16 42 02" src="https://github.com/cilium/hubble-ui/assets/1910449/72cb194f-1347-4807-afac-1ce98a57f79e">|
- Open Hubble UI and select a namespace
- Observe that the page does not have a scroll bar anymore on the entire body
- **!!!important!!!** Verify that if you move your mouse over the "lock" icons, the tooltup is still displayed:
_I could not test the last part …
> Service map page: remove unnecessary scroll

- src/domain/__tests__/labels.ts
- src/domain/labels.ts
Issue https://github.com/cilium/hubble-ui/issues/792.
This PR fixes a bug introduced in https://github.com/isovalent/hubble-ui-enterprise/pull/1108: the key `component` was wrongly added to the list of keys to retrieve an app app name from k8s labels.
- Removed `component`
|Before|After|
|---|---|
|<img width="1215" alt="Screenshot 2024-03-18 at 22 00 57" src="https://github.com/isovalent/hubble-ui-enterprise/assets/1910449/a88b56df-8557-4e95-ac9e-5dc331f87c07">|<img width="799" alt="Screenshot 2024-03-18 at 22 01 17" src="https://github.com/isovalent/hubble-ui-enterprise/assets/1910449/27459576-0bea-48b2-8b6e-398c901e8a01">|
None added.
- In a cluster, add a label such as `component` is suffixing it:
- `kubectl label pods crawler-7748bbc7b8-xr2vn app.kubernetes.io/component=api -n …
> Remove wrong key lookup for service name in k8s labels

- src/index.tsx
- src/router/Routes.tsx
Fix #854
Fix #889
This pull request fixes a bug which hubble-ui will not work if `hubble.ui.baseUrl` is specified to other than `/`.
after this pull-request, hubble-ui now correctly consider `<base href>` tag (if available) for:
* API path (previously hardcoded to `${location.origin}/api/`)
* react-router's base path (previously not specified, which causes default value: `/`)
side note: `<base href>` is changed by cillium's nginx, see https://github.com/cilium/cilium/blob/5a4fdc967a51146c15b65e5401ecb5d7decdd8d2/install/kubernetes/cilium/templates/hubble-ui/_nginx.tpl#L31
> fix: 404 Not Found error when baseUrl is not /

- backend/internal/config/prop_getters.go
The cilium-cli connectivity test treats warnings in the logs as test errors[^1]. This causes tests involving hubble-ui to fail[^2]. As these fallbacks aren't really warnings but rather
informative messsages, demote them to info level.
[^1]: https://github.com/cilium/cilium/pull/35723
[^2]: https://github.com/cilium/cilium-cli/actions/runs/12051244564/job/33601849065?pr=2869#step:13:541
> backend/internal/config: log env var fallback as info instead of warning

- src/components/ServiceMapApp/WelcomeScreen.scss
- src/components/ServiceMapApp/WelcomeScreen.tsx
- src/components/TopBar/index.tsx
On Hubble's main page, I changed the way the namespace's list appear under the "To begin select one of the namespaces:" text.
The namespaces are being shown using the Dropdown list Hubble uses on the top of the UI.
In the main page, the dropdown list will only appear in the middle of the screen, not anymore in the top portion of it.
After selecting a namespace and being redirected to the "flows" page, the list will reappear on the top.
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/dd17c22a-9266-452a-b423-c3e8a23e046c) | ![image](https://github.com/user-attachments/assets/7e70ac10-ef66-49c4-a891-436595b99db9)  |
> Updating home namespace list, enhancing the UI.

- src/components/TopBar/FlowsFilterInput.tsx
Migrate the deprecated MultiSelect2 to MultiSelect.
- Change MultiSelect2 to MultiSelect
n/a
- Open Hubble UI and select a namespace
- Observe that the filter input looks good in the top bar
- Click on a service card
- Check that the labels are still well rendered in the top bar
> Migrate blueprint MultiSelect2

- src/domain/filtering/__tests__/filter-service.test.ts
- src/domain/labels.ts
- src/domain/service-map/card.ts
- src/testing/data/services.ts
This PR adds support for incoming connections with ipv6 to be displayed as world instead of unkonwn
- Added corresponding labels
- Test for both work in ipv4 and ipv6
Not yet, i need to find an ipv6 cluster to test this
Added
- Open Hubble UI in a cluster with ipv6 traffic
- Check that the world is displayed, and that there is no Unknown app anymore
> Support world connection with ipv6

- src/router/Routes.tsx
this is basically a re-apply of fd6924bfc249242fc65fc233f6b02af552f405b6, since it is accidentally removed by d1bb05dd91f72e6ea02c386633e38d0b3bf63bdd
Fix #971
see more details in original pull request, https://github.com/cilium/hubble-ui/pull/941
> fix: 404 Not Found error when baseUrl is not / (again)
